// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:  
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQhsjI8SLGhl9dO4-nDftBWgPzMCunVlE',
    appId: '1:279329949546:web:70773ea8c7b2703e9a8713',
    messagingSenderId: '279329949546',
    projectId: 'appeov-23dbe',
    authDomain: 'appeov-23dbe.firebaseapp.com',
    storageBucket: 'appeov-23dbe.firebasestorage.app',
    measurementId: 'G-FSTKK1NGNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKtX19EmMB4Vk90SrZKTUT8pTCUG0AhZk',
    appId: '1:279329949546:android:9fa4a8ffb7ce1e359a8713',
    messagingSenderId: '279329949546',
    projectId: 'appeov-23dbe',
    storageBucket: 'appeov-23dbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC3bcKZ2UeXyOSSyAYrOflc_tRtEKwUME',
    appId: '1:279329949546:ios:eecaab79e9b6a6229a8713',
    messagingSenderId: '279329949546',
    projectId: 'appeov-23dbe',
    storageBucket: 'appeov-23dbe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC3bcKZ2UeXyOSSyAYrOflc_tRtEKwUME',
    appId: '1:279329949546:ios:eecaab79e9b6a6229a8713',
    messagingSenderId: '279329949546',
    projectId: 'appeov-23dbe',
    storageBucket: 'appeov-23dbe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQhsjI8SLGhl9dO4-nDftBWgPzMCunVlE',
    appId: '1:279329949546:web:1f3e1432d9dd582e9a8713',
    messagingSenderId: '279329949546',
    projectId: 'appeov-23dbe',
    authDomain: 'appeov-23dbe.firebaseapp.com',
    storageBucket: 'appeov-23dbe.firebasestorage.app',
    measurementId: 'G-ZBLBWKS0TV',
  );

}